#!/bin/sh
# This script has one line for each known working toolchain
# for this architecture.  Uncomment the one you want.
# Generated by generate-demo.pl from buildlogs/all.dats.txt

set -ex
TARBALLS_DIR=$HOME/downloads
RESULT_TOP=/opt/crosstool
export TARBALLS_DIR RESULT_TOP
GCC_LANGUAGES="c,c++"
export GCC_LANGUAGES

# Really, you should do the mkdir before running this,
# and chown /opt/crosstool to yourself so you don't need to run as root.
mkdir -p $RESULT_TOP

#eval `cat m68k.dat gcc-2.95.3-glibc-2.1.3.dat` sh all.sh --notest
#eval `cat m68k.dat gcc-2.95.3-glibc-2.2.2.dat` sh all.sh --notest
#eval `cat m68k.dat gcc-3.2.3-glibc-2.3.2.dat` sh all.sh --notest
#eval `cat m68k.dat gcc-3.3.6-glibc-2.2.2.dat` sh all.sh --notest
#eval `cat m68k.dat gcc-3.3.6-glibc-2.3.2.dat` sh all.sh --notest
#eval `cat m68k.dat gcc-3.3.6-glibc-2.3.2-tls.dat` sh all.sh --notest
#eval `cat m68k.dat gcc-3.3.6-glibc-2.3.5.dat` sh all.sh --notest
#eval `cat m68k.dat gcc-3.3.6-glibc-2.3.6.dat` sh all.sh --notest
#eval `cat m68k.dat gcc-3.4.5-glibc-2.2.2.dat` sh all.sh --notest
#eval `cat m68k.dat gcc-3.4.5-glibc-2.3.2.dat` sh all.sh --notest
#eval `cat m68k.dat gcc-3.4.5-glibc-2.3.2-tls.dat` sh all.sh --notest
#eval `cat m68k.dat gcc-3.4.5-glibc-2.3.5.dat` sh all.sh --notest
#eval `cat m68k.dat gcc-3.4.5-glibc-2.3.5-tls.dat` sh all.sh --notest
#eval `cat m68k.dat gcc-3.4.5-glibc-2.3.6.dat` sh all.sh --notest
#eval `cat m68k.dat gcc-3.4.5-glibc-2.3.6-tls.dat` sh all.sh --notest
#eval `cat m68k.dat gcc-4.0.2-glibc-2.2.2.dat` sh all.sh --notest
#eval `cat m68k.dat gcc-4.0.2-glibc-2.3.2.dat` sh all.sh --notest
#eval `cat m68k.dat gcc-4.0.2-glibc-2.3.2-tls.dat` sh all.sh --notest
#eval `cat m68k.dat gcc-4.1.0-glibc-2.2.2.dat` sh all.sh --notest
#eval `cat m68k.dat gcc-4.1.0-glibc-2.3.2.dat` sh all.sh --notest
#eval `cat m68k.dat gcc-4.1.0-glibc-2.3.2-tls.dat` sh all.sh --notest
#eval `cat m68k.dat gcc-4.1.0-glibc-2.3.5.dat` sh all.sh --notest
#eval `cat m68k.dat gcc-4.1.0-glibc-2.3.5-tls.dat` sh all.sh --notest
#eval `cat m68k.dat gcc-4.1.0-glibc-2.3.6.dat` sh all.sh --notest
eval `cat m68k.dat gcc-4.1.0-glibc-2.3.6-tls.dat` sh all.sh --notest

echo Done.
